connections:
  - ssh.web-01

remote_folder: "/root/hade"

frontend:
  pre_action:
    - "pwd"
  post_action:
    - "pwd"

backend:
  goos: linux
  goarch: amd64
  pre_action:
    - "rm /root/hade/hade || echo 0 "
    - "rm -rf /root/hade/config || echo 0"
  post_action:
    - "chmod 777 /root/hade/hade"
    - "mkdir -p /root/hade/storage/runtime/"
    - "mkdir -p /root/hade/storage/log/"
    - "cd /root/hade && ./hade app restart"
