version: '3'
services:
  # base 服务
  base-service:
    build:
      context: ../../user
      dockerfile: Dockerfile
    image: base-service:2.0.0
    container_name: base-cap-service
    restart: always
    ports:
      - "5000:5000"
      - "8080:8080"