server:
  port: 8090


# Mybatis相关的配置
mybatis:
  type-aliases-package: com.vincent.pojo    # 所有数据库表逆向后所一一映射的实体类 Entity/Bean/POJO
  mapper-locations: classpath:mapper/*.xml # 所有mapper映射的文件所在目录位置
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl # 开启mybatis的日志实现，可以在控制台打印输出sql语句
